version: "2"

services:
  web:
   image: nginx:latest
   mem_limit: 96m
   container_name: Nginx
   ports:
   - "80:80"
   volumes:
   - ./public:/public
   - ./src/site.conf:/etc/nginx/conf.d/site.conf
   - ./src/nginx/logs:/var/log/nginx/

  php:
   build:
    context: ./src/php7
   mem_limit: 96m
   container_name: PHP7
   volumes:
   - ./public:/public

  db:
   image: mariadb:latest
   mem_limit: 96m
   container_name: MariaDB
   volumes:
    - ./src/mariadb:/var/lib/mysql
   environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
    MYSQL_DATABASE: dev
    MYSQL_USER: dev
    MYSQL_PASSWORD: dev123
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
   ports:
   - "3366:3306"
   #expose:
   #- 3306

  pma:
   image: phpmyadmin/phpmyadmin
   mem_limit: 96m
   container_name: phpMyAdmin
   environment:
    PMA_ARBITRARY: 1
    PMA_HOST: db
    PMA_USER: dev
    PMA_PASSWORD: dev123
    PHP_UPLOAD_MAX_FILESIZE: 1G
    PHP_MAX_INPUT_VARS: 1G
   restart: always
   ports:
   - "8001:80"
   volumes:
   - ./src/sessions:/sessions 
